# 리눅스 권한 (root x)
user nginx;

# 워커 프로세스 수 (CPU 코어 수에 따라 자동 설정)
worker_processes auto; 

# 프로세스 ID 파일 경로
pid /var/run/nginx.pid;

events {
    # 커넥션 한계
    worker_connections 4096; 

    # 여러 요청 처리
    multi_accept on;
}

http {
    # 파일 형식 포함
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # 파일 전송
    sendfile on;

    server {
        listen 80;
        server_name localhost;

        underscores_in_headers on;

        root /usr/share/nginx/html;
        index index.html index.htm;

        # SPA 
        location / {
            try_files $uri $uri/ /index.html;
        }

        # API 프록시 설정
        location /api/ {
            proxy_pass http://backend-app:8888;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 로고 아이콘 프록시 설정
        location /icons/ {
            proxy_pass https://cdn.simpleicons.org/;
            proxy_set_header Host cdn.simpleicons.org;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_cache_valid 200 24h;
            add_header Access-Control-Allow-Origin *;
        }

        # Static files caching (이미지, JS, CSS 캐싱)
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}