version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-md
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: md
      MYSQL_USER: yi5oyu
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - mysql_md_data:/var/lib/mysql
    # restart: always

  redis:
    image: redis:latest
    container_name: redis-md
    ports:
      - '6380:6379'
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    volumes:
      - redis_md_data:/data
    networks:
      - app-network

  # playwright-mcp:
  #   image: mcr.microsoft.com/playwright/mcp
  #   container_name: playwright-mcp
  #   ports:
  #     - '8931:8931'
  #   stdin_open: true
  #   init: true
  #   entrypoint:
  #     ['node', 'cli.js', '--headless', '--browser', 'chromium', '--no-sandbox', '--port', '8931']
  #   networks:
  #     - app-network

volumes:
  mysql_md_data:
  redis_md_data:

networks:
  app-network:
    driver: bridge
