version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-md
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: md
      MYSQL_USER: yi5oyu
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - mysql_md_data:/var/lib/mysql
    # restart: always

volumes:
  mysql_md_data:
