spring:
  application:
    name: mcp-server
  datasource:
    url: jdbc:mysql://localhost:3306/md?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yi5oyu
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  ai:
    mcp:
      server:
        name: sb-mcp-server
        version: 1.0.0
        enabled: true

server:
  port: 9888
