name: monitoring

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - '9000:9000'
      - '9443:9443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - monitoring_network
      - writemd_app-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - monitoring_network
      - writemd_app-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    networks:
      - monitoring_network
    restart: unless-stopped

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    ports:
      - '9104:9104'
    environment:
      - MYSQLD_EXPORTER_PASSWORD=${MYSQL_USER_PASSWORD}
    command:
      - '--mysqld.username=yi5oyu'
      - '--mysqld.address=mysql-md:3306'
    networks:
      - monitoring_network
      - writemd_app-network
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    ports:
      - '9121:9121'
    environment:
      - REDIS_ADDR=redis-md:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - monitoring_network
      - writemd_app-network
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring_network
      - writemd_app-network
    restart: unless-stopped

volumes:
  portainer_data:
    name: monitoring_portainer_data
  prometheus_data:
    name: monitoring_prometheus_data
  grafana_data:
    name: monitoring_grafana_data

networks:
  monitoring_network:
    name: monitoring_network
    driver: bridge
  writemd_app-network:
    external: true
    name: writemd_app-network
