spring:
  application:
    name: backend
  # 보안
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: 'http://localhost:8888/login/oauth2/code/github'
            scope: read:user,user:email
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "info"
  endpoint:
    health:
      show-details: always
  server:
    port: 8889

server:
  port: 8888
